# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afa82ee451175b253bdc196acb97030ea1a7d1bff33e2e0e5f24f0b4dcbfe0729b49787448e05bcb4d3e84f18ebf96839f4651575954ada7f1ddcb559bcdbca7

test:
  secret_key_base: 3ec7c2896d40a964b3e34b147a95c517f48a1cf653cdeb301f98873d07d8d94773dd2568d1b8c01101aa29e469b6e0176568f4b10845e00dde05f51e76c4adf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
